@startuml
'https://plantuml.com/class-diagram

class Tour {
    -String name;
    -String tourDescription;
    -String from;
    -String to;
    -TransportType transportType;
    -double tourDistance;
    -int estimatedTime;
    -String routeInformation;
    +Getter();
    +Setter();
}

class TourLogs {
    -String dateTime;
    -String comment;
    -int difficulty;
    -double totalDistance;
    -double totalTime;
    -int rating;
    +Getter();
    +Setter();
}

class Import {
    +importFromCSVFile();
}

class Export {
    +createCSVFile();
    +exportToCSV();
}

abstract class Report {

}

class TourReport {
    -Tour tour;
    -String tourLog;
    +Getter();
    +Setter();
}

class SummarizeReport {

}

class Statistics {
    +calculateAnalysis();
}

enum TransportType {
    BIKE
    HIKE
    RUNNING
    VACATION
}

Report --|> SummarizeReport
Report --|> TourReport

@enduml